### ISSUE TITLE
Digest is not working (Digest, Tag, Helm)

### ISSUE THREAD

**Issue by buddhi-desilva** [argoproj-labs/argocd-image-updater#259] opened 2021-09-16 20:24 UTC
**Describe the bug**
argocd-image-updater: v0.10.3
argocd: v2.1.2
gitrepo: helm

Strategy
```
argocd-image-updater.argoproj.io/write-back-method: argocd
argocd-image-updater.argoproj.io/image-list: myimagealias=gcr.io/project-name/images-path/my-image-name:my-tag-name
argocd-image-updater.argoproj.io/myimagealias.update-strategy: digest

```

I'm using the digest strategy for image updating and from argocd-image-updater end all seems to work fine, and I'm getting the successfully updated message. Yet ArgoCD doesn't seem to update the image.

```
time="2021-09-16T19:47:35Z" level=info msg="Successfully updated the live application spec" application=dev-environment
```

When I check the Argo CD, I can see the following has been added to parameters, but it does't trigger an update.
```
image.name
  gcr.io/project-name/images-path/my-image-name
image.tag
 sha256:xxxxxxx
```

My approach / requirement is to have  argocd as the write-back method and only the team members updating the deployment repo with image details and repo tags per each environment.

1. Can anyone tell me what I might be doing wrong here?
2. Any help on fixing this issue is appreciated

**Comment by jannfis** [comment] 2021-09-17 05:54
Hey @buddhi-desilva, I suspect that you will need a different set of parameters to be updated instead if `image.name` and `image.tag` in order for your Helm charts to be correctly rendered.

Please have a look at https://argocd-image-updater.readthedocs.io/en/stable/configuration/images/#specifying-helm-parameter-names

Also, for `digest` strategy, keep in mind that if your Chart constructs the image slug such as

```
image: {{ image-name }}:{{ image-tag }}
```

that might not work with digest, because it would result in something like `some-image:sha256:abef...`, but needs to be `some-image@sha256:abef...`. This is an outstanding bug, which will be fixed with v0.11 (because it might break workarounds in place).

**Comment by buddhi-desilva** [comment] 2021-09-17 07:16
Hi @jannfis, i did try the helm parameters name thing as well, but it didn't work either (I think I've exhausted all the options related to digest strategy).

When I look at the image-updater logs:

Helm / Non Helm config log messages shows pretty much the same:
```
time="2021-09-17T06:57:30Z" level=info msg="Successfully updated image 'gcr.io/project-name/images-path/my-image-name@dummy' to 'gcr.io/project-name/images-path/my-image-name@sha256:4e47031bd2549fca9b0d99a36fdc3ebd72022e8510e3efc21f38bc1dca47fe3c', but pending spec update (dry run=false)" alias= myimagealias application=some-environment image_name=project-name/images-path/my-image-name image_tag=dummy registry=gcr.io
```

However the parameters updated in the Application manifest are different:

**HELM**
```
parameters:
  - name: image.repository
    value: gcr.io/project-name/images-path/my-image-name
    forceString: true
  - name: image.tag
    value: >-
      sha256:4e47031bd2549fca9b0d99a36fdc3ebd72022e8510e3efc21f38bc1dca47fe3c
    forceString: true
```

**Non-HELM Config**
```
parameters:
  - name: image.name
    value: gcr.io/project-name/images-path/my-image-name
    forceString: true
  - name: image.tag
    value: >-
      sha256:4e47031bd2549fca9b0d99a36fdc3ebd72022e8510e3efc21f38bc1dca47fe3c
    forceString: true
```

None of them work though..

I think I got to try the name / lexical sort strategy and name the images accordingly at the build time since this isn't seem to work.

**Comment by jannfis** [comment] 2021-09-17 07:42
What exactly do you mean by "helm" and "non-helm" config? From the updates, it seems clear that the tag update is successful. But in order for Argo CD to render new manifests, your chart needs to consider these parameters.

What are the parameters your Chart uses for setting the image?

**Comment by buddhi-desilva** [comment] 2021-09-17 14:14
Sorry if i wasn't clear: What i meant was "with helm parameters":
```
....
# argocd-image-updater.argoproj.io/myimagealias.helm.image-tag: image.tag
# argocd-image-updater.argoproj.io/myimagealias.helm.image-name: image.repository
...
```

and "without helm parameters being set":
```
argocd-image-updater.argoproj.io/write-back-method: argocd
argocd-image-updater.argoproj.io/image-list: myimagealias=gcr.io/project-name/images-path/my-image-name:my-tag-name
argocd-image-updater.argoproj.io/myimagealias.update-strategy: digest
```

Chart is using these parameters: 
```
image.tag
image.repository
```


As you said updating from image-updater to argocd seems successful. However, what I don't know is what are the exact params expected by ArgoCD to trigger an update from that end.

**Comment by buddhi-desilva** [comment] 2021-09-18 05:58
@jannfis, i tried using 
```
argocd-image-updater.argoproj.io/myimagealias.helm.image-spec: image.repository:image.tag
```
and the Application gets updated this way.
```
parameters:
  - name: 'image.repository:image.tag'
    value: >-
      gcr.io/project-name/images-path/my-image-name@sha256:3a6b1c5...
    forceString: true
```

As you've mentioned it is updating to the pattern of `some-image@sha256:abef...`. However, the image isn't getting updated from the ArgoCD end.

Can someone help me out here and point me at the direction I should try to resolve the issue?

**Comment by buddhi-desilva** [comment] 2021-09-18 08:44
> @jannfis, i tried using
> 
> ```
> argocd-image-updater.argoproj.io/myimagealias.helm.image-spec: image.repository:image.tag
> ```
> 
> and the Application gets updated this way.
> 
> ```
> parameters:
>   - name: 'image.repository:image.tag'
>     value: >-
>       gcr.io/project-name/images-path/my-image-name@sha256:3a6b1c5...
>     forceString: true
> ```
> 
> As you've mentioned it is updating to the pattern of `some-image@sha256:abef...`. However, the image isn't getting updated from the ArgoCD end.
> 
> Can someone help me out here and point me at the direction I should try to resolve the issue?

### I can verify this method works.
**For some reason it didn't work for the first few cycles (may be due to some caching issue). But it started to work**. Will be setting up for several microservices on the same environment and hopefully it'll work..

@jannfis thanks! And the updater keep pushing updates even after the image is updated / current on the cluster. Is it the expected behaviour?

**Comment by SWBSanjeewa** [comment] 2021-09-23 05:05
Digest may not work if your helm chart's image is constructed as 
     image: {{ image-name }}:{{ image-tag }}
Could get digest work by creating the helm chart by setting the image as 
     image: {{ image-name }}@{{ image-tag }}
We may need to go like that until it is fixed in argocd-image-updater v0.11

ArgoCD application annotation should be set as
argocd-image-updater.argoproj.io/image-list=myimage=abc.com/myimage:latest 
argocd-image-updater.argoproj.io/myimage.update-strategy=digest

**Comment by buddhi-desilva** [comment] 2021-09-23 12:13
@SWBSanjeewa did you check the code and the logs i had posted. It worked for me without changing the helm chart. I used `image-spec` instead of `image-tag` and `image-name` and it seemed to work. Now I'm struggling with another issue #261 where only a single image is updated from the list of images. Do you think it could be related what you've mentioned?

**Comment by imdbere** [comment] 2021-11-24 08:10
Are there any updates on this ? What is the recommended way to use the `digest` strategy with helm?

**Comment by ElArtista** [comment] 2021-12-10 15:53
New to argocd-image-updater, just built it from master.
Issue still persists.

**Comment by ElArtista** [comment] 2021-12-11 21:12
@buddhi-desilva @jannfis the proposed workaround with:
```
argocd-image-updater.argoproj.io/myimagealias.helm.image-spec: image.repository:image.tag
```
seems to generate valid image references in the form of `someimage@sha256:longhashhere` but it does not work anymore.
Firstly, this branch:
https://github.com/argoproj-labs/argocd-image-updater/blob/c12271a11bf4a88d7c02dcab494dcdeb78e3ae7a/pkg/argocd/update.go#L260
seems to cause a loop and forces the image to be updated in each cycle.

Secondly, the reason that the workaround generates valid image references is that when `image-spec` is specified, a little below inside this call:
https://github.com/argoproj-labs/argocd-image-updater/blob/c12271a11bf4a88d7c02dcab494dcdeb78e3ae7a/pkg/argocd/update.go#L269
-> https://github.com/argoproj-labs/argocd-image-updater/blob/c12271a11bf4a88d7c02dcab494dcdeb78e3ae7a/pkg/argocd/update.go#L356
-> https://github.com/argoproj-labs/argocd-image-updater/blob/c12271a11bf4a88d7c02dcab494dcdeb78e3ae7a/pkg/argocd/argocd.go#L371
-> https://github.com/argoproj-labs/argocd-image-updater/blob/c12271a11bf4a88d7c02dcab494dcdeb78e3ae7a/pkg/image/image.go#L61

it checks if the tag is a digest type and creates the full image name correctly.

Even with that though, `image-spec` annotation/param seems to have no effect at all at the application and the loop continues with the below output again and again:
```
time="2021-12-11T21:06:52Z" level=trace msg="processing app 'cicd-sample' of type 'Helm'"
time="2021-12-11T21:06:52Z" level=info msg="Starting image update cycle, considering 1 annotated application(s) for update"
time="2021-12-11T21:06:52Z" level=debug msg="Processing application cicd-sample"
time="2021-12-11T21:06:52Z" level=debug msg="Considering this image for update" alias=cicd-sample application=cicd-sample image_name=cicd-sample image_tag=latest registry=
time="2021-12-11T21:06:52Z" level=debug msg="Using version constraint 'latest' when looking for a new tag" alias=cicd-sample application=cicd-sample image_name=cicd-sample image_tag=latest registry=
time="2021-12-11T21:06:52Z" level=trace msg="found update strategy digest in argocd-image-updater.argoproj.io/cicd-sample.update-strategy"
time="2021-12-11T21:06:52Z" level=trace msg="No match annotation argocd-image-updater.argoproj.io/cicd-sample.tag-match found"
time="2021-12-11T21:06:52Z" level=trace msg="No ignore-tags annotation argocd-image-updater.argoproj.io/cicd-sample.ignore-tags found"
time="2021-12-11T21:06:52Z" level=trace msg="No secret annotation argocd-image-updater.argoproj.io/cicd-sample.pull-secret found"
time="2021-12-11T21:06:52Z" level=debug msg="Using canonical image name 'library/cicd-sample' for image 'cicd-sample'"
time="2021-12-11T21:06:52Z" level=trace msg="http://registry-docker-registry:5000/v2/library/cicd-sample/tags/list"
time="2021-12-11T21:06:52Z" level=trace msg="Getting manifest for image library/cicd-sample:latest (operation 1/1)"
time="2021-12-11T21:06:52Z" level=trace msg="acquired metadata semaphore"
time="2021-12-11T21:06:52Z" level=trace msg="http://registry-docker-registry:5000/v2/library/cicd-sample/manifests/latest"
time="2021-12-11T21:06:52Z" level=trace msg="http://registry-docker-registry:5000/v2/library/cicd-sample/blobs/sha256:0e5e07d996db2b801c7f3f4763fdabbee4b198ec871eb908efd9a0a07e100ae1"
time="2021-12-11T21:06:52Z" level=trace msg="v2 SHA digest is sha256:0efc59891e25121140b3dbfd41c53d6868e4661ab19a3533e3516ba7e9dd2b75"
time="2021-12-11T21:06:52Z" level=trace msg="Found date 2021-12-11 20:54:00.620884518 +0000 UTC"
time="2021-12-11T21:06:52Z" level=trace msg="released semaphore and terminated waitgroup"
time="2021-12-11T21:06:52Z" level=trace msg="List of available tags found: [latest]" alias=cicd-sample application=cicd-sample image_name=cicd-sample image_tag=latest registry=
time="2021-12-11T21:06:52Z" level=trace msg="Finding out whether to consider latest for being updateable" image="cicd-sample:latest"
time="2021-12-11T21:06:52Z" level=debug msg="found 1 from 1 tags eligible for consideration" image="cicd-sample:latest"
time="2021-12-11T21:06:52Z" level=trace msg="Setting dummy digest for image cicd-sample:latest"
time="2021-12-11T21:06:52Z" level=info msg="Setting new image to cicd-sample@sha256:0efc59891e25121140b3dbfd41c53d6868e4661ab19a3533e3516ba7e9dd2b75" alias=cicd-sample application=cicd-sample image_
time="2021-12-11T21:06:52Z" level=debug msg="target parameters: image-spec=image.repository:image.tag image-name=, image-tag=" application=cicd-sample image=cicd-sample
time="2021-12-11T21:06:52Z" level=info msg="Successfully updated image 'cicd-sample@dummy' to 'cicd-sample@sha256:0efc59891e25121140b3dbfd41c53d6868e4661ab19a3533e3516ba7e9dd2b75', but pending spec
time="2021-12-11T21:06:52Z" level=debug msg="Using commit message: "
time="2021-12-11T21:06:52Z" level=info msg="Committing 1 parameter update(s) for application cicd-sample" application=cicd-sample
time="2021-12-11T21:06:52Z" level=info msg="Successfully updated the live application spec" application=cicd-sample
time="2021-12-11T21:06:52Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=1 errors=0"
```
Reproduced with below annotations:
```
    argocd-image-updater.argoproj.io/image-list: cicd-sample=cicd-sample:latest
    argocd-image-updater.argoproj.io/cicd-sample.update-strategy: digest
    argocd-image-updater.argoproj.io/cicd-sample.helm.image-spec: image.repository:image.tag
```

**Comment by ElArtista** [comment] 2021-12-11 22:04
The above case can be confirmed with any helm chart, by executing:
```
helm template cicd-sample chart --set image.repository:image.tag=someimage:sometag@sha256:abcdef12345
```
The result in output is identical to the original (unchanged) chart.
That means that setting the `image.repository:image.tag` param has no effect by default in any chart (except if specifically implemented to do so)

**Closed** 2021-12-16 20:05 UTC
Labels: bug
